server:
  port: ${SERVER_PORT:4004}

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        # lets CORS work for non-HandlerMapping paths too (handy across versions)
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - X-User-Id
              - X-Email
              - X-First-Name
              - X-Last-Name
            allowCredentials: true

      routes:
        # ---- AUTH SERVICE (exposed under /auth/...) ----
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1   # /auth/register -> /register to backend

        # ---- PORTFOLIO SERVICE ----
        - id: portfolio-service
          uri: ${PORTFOLIO_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/portfolio/**,/market/**,/trades/**
          filters:
            - StripPrefix=0

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
